from __future__ import annotations

import socket
import struct
from dataclasses import dataclass, field

from src.domain.entities.topology import Topology


@dataclass
class ResolvedRouteRule:
    destination: str
    destination_type: str
    target_type: str           # IGW, NAT, DRG, LPG, SGW, PRIVATE_IP, UNKNOWN
    target_ocid: str
    target_name: str
    is_default_route: bool
    is_local: bool


@dataclass
class RouteFlow:
    subnet_ocid: str
    subnet_name: str
    route_table_ocid: str
    route_table_name: str
    rules: list[ResolvedRouteRule] = field(default_factory=list)


@dataclass
class DRGFlow:
    drg_ocid: str
    drg_name: str
    route_table_ocid: str
    route_table_name: str
    rules: list[dict] = field(default_factory=list)


@dataclass
class FlowWarning:
    severity: str   # info, warning, error
    code: str       # BLACKHOLE, MISSING_RT, OVERLAP_CIDR, NO_DEFAULT, OPEN_SECURITY
    message: str
    affected_resources: list[str] = field(default_factory=list)


@dataclass
class AnalysisResult:
    flows: list[RouteFlow] = field(default_factory=list)
    drg_flows: list[DRGFlow] = field(default_factory=list)
    warnings: list[FlowWarning] = field(default_factory=list)
    subnet_to_route_table: dict[str, str] = field(default_factory=dict)
    route_table_to_subnets: dict[str, list[str]] = field(default_factory=dict)
    gateway_to_route_rules: dict[str, list[str]] = field(default_factory=dict)


EntityMap = dict[str, tuple[str, str]]


class RouteAnalyzer:

    def analyze(self, topology: Topology) -> AnalysisResult:
        result = AnalysisResult()
        emap = self._build_entity_map(topology)
        for subnet in topology.subnets:
            flow = self._analyze_subnet(subnet, topology, emap, result)
            if flow:
                result.flows.append(flow)
        for drg in topology.drgs:
            self._analyze_drg(drg, topology, result)
        self._detect_overlapping_cidrs(topology, result)
        return result

    def _build_entity_map(self, topology: Topology) -> EntityMap:
        m: EntityMap = {}
        for g in topology.internet_gateways:
            m[g.ocid] = ("IGW", g.display_name)
        for g in topology.nat_gateways:
            m[g.ocid] = ("NAT", g.display_name)
        for g in topology.service_gateways:
            m[g.ocid] = ("SGW", g.display_name)
        for d in topology.drgs:
            m[d.ocid] = ("DRG", d.display_name)
        for l in topology.local_peering_gateways:
            m[l.ocid] = ("LPG", l.display_name)
        for a in topology.drg_attachments:
            m[a.ocid] = ("DRG_ATTACHMENT", a.display_name)
        return m

    @staticmethod
    def _classify(ocid: str, emap: EntityMap) -> tuple[str, str]:
        if not ocid:
            return ("UNKNOWN", "Unknown")
        if ocid in emap:
            return emap[ocid]
        return ("PRIVATE_IP", ocid) if "privateip" in ocid.lower() else ("UNKNOWN", ocid)

    def _analyze_subnet(self, subnet, topology, emap, result):
        rt_id = subnet.route_table_id
        rt = next((r for r in topology.route_tables if r.ocid == rt_id), None)
        if not rt:
            if rt_id:
                result.warnings.append(FlowWarning(
                    "warning", "MISSING_RT",
                    f"Subnet '{subnet.display_name}' references missing route table.",
                    [subnet.ocid, rt_id]))
            return None

        result.subnet_to_route_table[subnet.ocid] = rt.ocid
        result.route_table_to_subnets.setdefault(rt.ocid, []).append(subnet.ocid)

        rules = [r for r in topology.route_rules if r.route_table_id == rt.ocid]
        resolved, has_default = [], False

        for rule in rules:
            ttype, tname = self._classify(rule.network_entity_id, emap)
            is_def = rule.destination in ("0.0.0.0/0", "::/0")
            has_default = has_default or is_def

            if ttype == "UNKNOWN" and rule.network_entity_id:
                result.warnings.append(FlowWarning(
                    "error", "BLACKHOLE",
                    f"Route in '{rt.display_name}' targets unknown entity.",
                    [rt.ocid, rule.network_entity_id]))

            resolved.append(ResolvedRouteRule(
                rule.destination, rule.destination_type, ttype,
                rule.network_entity_id, tname, is_def,
                ttype in ("LPG", "PRIVATE_IP")))
            result.gateway_to_route_rules.setdefault(rule.network_entity_id, []).append(rule.destination)

        # Only warn about missing default route for non-DRG, non-specialized route tables
        if not has_default and resolved and not rt.display_name.startswith("Autogenerated"):
            result.warnings.append(FlowWarning(
                "info", "NO_DEFAULT",
                f"Subnet '{subnet.display_name}' route table '{rt.display_name}' has no default route (0.0.0.0/0).",
                [subnet.ocid, rt.ocid]))

        return RouteFlow(subnet.ocid, subnet.display_name, rt.ocid, rt.display_name, resolved)

    def _analyze_drg(self, drg, topology, result):
        att_names = {a.ocid: a.display_name for a in topology.drg_attachments}
        for rt in topology.drg_route_tables:
            if rt.drg_id != drg.ocid:
                continue
            rules = [{"destination": r.destination, "destination_type": r.destination_type,
                       "next_hop": att_names.get(r.next_hop_drg_attachment_id, r.next_hop_drg_attachment_id)}
                      for r in topology.drg_route_rules if r.drg_route_table_id == rt.ocid]
            result.drg_flows.append(DRGFlow(drg.ocid, drg.display_name, rt.ocid, rt.display_name, rules))

    def _detect_overlapping_cidrs(self, topology, result):
        by_vcn: dict[str, list] = {}
        for s in topology.subnets:
            by_vcn.setdefault(s.vcn_id, []).append(s)
        for subnets in by_vcn.values():
            ranges = [(r, s) for s in subnets if (r := self._cidr_range(s.cidr_block))]
            for i in range(len(ranges)):
                for j in range(i + 1, len(ranges)):
                    (a0, a1), sa = ranges[i]
                    (b0, b1), sb = ranges[j]
                    if a1 >= b0 and b1 >= a0:
                        result.warnings.append(FlowWarning(
                            "warning", "OVERLAP_CIDR",
                            f"Subnets '{sa.display_name}' and '{sb.display_name}' overlap.",
                            [sa.ocid, sb.ocid]))

    @staticmethod
    def _cidr_range(cidr: str) -> tuple[int, int] | None:
        try:
            addr, pfx = cidr.split("/")
            n = struct.unpack("!I", socket.inet_aton(addr))[0]
            mask = (0xFFFFFFFF << (32 - int(pfx))) & 0xFFFFFFFF
            start = n & mask
            return (start, start | ~mask & 0xFFFFFFFF)
        except (ValueError, OSError):
            return None
